#!/bin/sh

git clone --recursive git@github.com:3tty0n/.emacs.d.git ~/.emacs.d

if [ ! -d ~/.cask ]; then
    curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
fi

if [ -x "$(which opam)"]; then
    opam user-setup install
fi

if [ ! -d ~/.emacs.d/elisp/opam-user-setup.el ]; then
    opam-user-setup install
fi
