(source gnu)
(source melpa)

;; cask
(depends-on "cask")
(depends-on "cask-mode")
(depends-on "pallet")

(depends-on "nlinum")
(depends-on "rainbow-delimiters")

;; helm
(depends-on "helm")
(depends-on "helm-swoop")
(depends-on "helm-ls-git")
(depends-on "helm-git-grep")

;; ivy and counsel
(depends-on "ivy")
(depends-on "counsel")
(depends-on "counsel")
(depends-on "swiper")

;; fzf
(depends-on "fzf")

(depends-on "elscreen")
(depends-on "wgrep")
(depends-on "smartparens")
(depends-on "multiple-cursors")
(depends-on "undo-tree")

;; internal
(depends-on "exec-path-from-shell")
(depends-on "neotree")
(depends-on "all-the-icons")

;; git
(depends-on "magit")
(depends-on "git-gutter+")

;; theme
(depends-on "molokai-theme")
(depends-on "cyberpunk-theme")
(depends-on "spacemacs-theme")
(depends-on "powerline")

;; flycheck
(depends-on "flycheck")
(depends-on "flycheck-cask")

;; completion
;; company
(depends-on "company")
(depends-on "company-quickhelp")
(depends-on "company-c-headers")
(depends-on "company-flx")

;; ya-family
(depends-on "yasnippet")
(depends-on "yascroll")
(depends-on "yatex")

;; scala
(depends-on "ensime")
(depends-on "scala-mode")
(depends-on "sbt-mode")

;; c
(depends-on "irony")

;; racket
(depends-on "racket-mode")

;; markdown
(depends-on "markdown-mode")

;; yaml
(depends-on "yaml-mode")

;; kunernetes
(depends-on "kubernetes")

;; docker
(depends-on "docker")
